import pandas as pd
import tarfile
import os
import matplotlib.pyplot as plt
import numpy as np
df1 = pd.read_csv('LEE.stuff/waveform1BHNS.out', sep=r'\s+', header=None, skiprows=1, engine='python')
df2 = pd.read_csv('LEE.stuff/waveform2BHNS.out', sep=r'\s+', header=None, skiprows=1, engine='python')
df3 = pd.read_csv('LEE.stuff/waveform3BHNS.out', sep=r'\s+', header=None, skiprows=1, engine='python')
df4 = pd.read_csv('LEE.stuff/waveform4BHNS.out', sep=r'\s+', header=None, skiprows=1, engine='python')
df5 = pd.read_csv('LEE.stuff/waveform5BHNS.out', sep=r'\s+', header=None, skiprows=1, engine='python')
df1.columns = ['t (sec)', 'rh+ (cm)', 'rhx (cm)']
df2.columns = ['t (sec)', 'rh+ (cm)', 'rhx (cm)']
df3.columns = ['t (sec)', 'rh+ (cm)', 'rhx (cm)']
df4.columns = ['t (sec)', 'rh+ (cm)', 'rhx (cm)']
df5.columns = ['t (sec)', 'rh+ (cm)', 'rhx (cm)']
dfc = pd.concat([df1, df2, df3, df4, df5], ignore_index=True)
print('Waveform 1 stats:', df1.describe(), df1.corr())
print('Waveform 2 stats:', df2.describe(), df2.corr())
print('Waveform 3 stats:', df3.describe(), df3.corr())
print('Waveform 4 stats:', df4.describe(), df4.corr())
print('Waveform 5 stats:', df5.describe(), df5.corr())
# some quick stats to get a better understanding of the combined data.
stats = dfc.describe()
print('combined statistics', stats)
print('info', dfc.info())
dfc.columns = ['t (sec)', 'rh+ (cm)', 'rhx (cm)']
print('Missing Values:', dfc.isnull().sum())
print('combined correlation', dfc.corr())
# quick visulizations of h+ and hx waveforms in respect to time to give you a better idea of what a gravitational wave looks like. A lot of repetition.
plt.figure(figsize=(10, 6))
plt.plot(df1['t (sec)'], df1['rh+ (cm)'], alpha=0.5)
plt.title('Waveform 1: rh+ vs Time')
plt.xlabel('Time (sec)')
plt.ylabel('rh+ (cm)')
plt.grid()
plt.show()
plt.figure(figsize=(10, 6))
plt.plot(df1['t (sec)'], df1['rhx (cm)'], alpha=0.5)
plt.title('Waveform 1: rhx vs Time')
plt.xlabel('Time (sec)')
plt.ylabel('rhx (cm)')
plt.grid()
plt.show()
plt.figure(figsize=(10, 6))
plt.plot(df2['t (sec)'], df2['rh+ (cm)'], alpha=0.5)
plt.title('Waveform 2: rh+ vs Time')   
plt.xlabel('Time (sec)')
plt.ylabel('rh+ (cm)')
plt.grid()
plt.show()
plt.figure(figsize=(10, 6))
plt.plot(df2['t (sec)'], df2['rhx (cm)'], alpha=0.5)
plt.title('Waveform 2: rhx vs Time')
plt.xlabel('Time (sec)')
plt.ylabel('rhx (cm)')
plt.grid()
plt.show()
plt.figure(figsize=(10, 6))
plt.plot(df3['t (sec)'], df3['rh+ (cm)'], alpha=0.5)
plt.title('Waveform 3: rh+ vs Time')
plt.xlabel('Time (sec)')
plt.ylabel('rh+ (cm)')
plt.grid()
plt.show()
plt.figure(figsize=(10, 6))
plt.plot(df3['t (sec)'], df3['rhx (cm)'], alpha=0.5)
plt.title('Waveform 3: rhx vs Time')
plt.xlabel('Time (sec)')
plt.ylabel('rhx (cm)')
plt.grid()
plt.show()
plt.figure(figsize=(10, 6))
plt.plot(df4['t (sec)'], df4['rh+ (cm)'], alpha=0.5)
plt.title('Waveform 4: rh+ vs Time')
plt.xlabel('Time (sec)')
plt.ylabel('rh+ (cm)')
plt.grid()
plt.show()
plt.figure(figsize=(10, 6))
plt.plot(df4['t (sec)'], df4['rhx (cm)'], alpha=0.5)
plt.title('Waveform 4: rhx vs Time')
plt.xlabel('Time (sec)')
plt.ylabel('rhx (cm)')
plt.grid()
plt.show()
plt.figure(figsize=(10, 6))
plt.plot(df5['t (sec)'], df5['rh+ (cm)'], alpha=0.5)
plt.title('Waveform 5: rh+ vs Time')
plt.xlabel('Time (sec)')
plt.ylabel('rh+ (cm)')
plt.grid()
plt.show()
plt.figure(figsize=(10, 6))
plt.plot(df5['t (sec)'], df5['rhx (cm)'], alpha=0.5)
plt.title('Waveform 5: rhx vs Time')
plt.xlabel('Time (sec)')
plt.ylabel('rhx (cm)')
plt.grid()
plt.show()
# these are visualization of all of the waveforms(respectivly) together to give a clearer undestanding of the influence of different parameters.
plt.figure(figsize=(10, 6))
#γ is the Lorentz factor (time dilation/length contraction factor) in gravitational wave physics. it is one of the parameters that was changed in each simulation.
plt.plot(df1['t (sec)'], df1['rh+ (cm)'], alpha=0.5, label='Simulation 1 (γ=3.0)')
plt.plot(df2['t (sec)'], df2['rh+ (cm)'], alpha=0.5, label='Simulation 2 (γ=2.0)')
plt.plot(df3['t (sec)'], df3['rh+ (cm)'], alpha=0.5, label='Simulation 3 (γ=5/3)')
plt.plot(df4['t (sec)'], df4['rh+ (cm)'], alpha=0.5, label='Simulation 4 (γ=3.0)')
plt.plot(df5['t (sec)'], df5['rh+ (cm)'], alpha=0.5, label='Simulation 5 (γ=5/3)')
plt.title('All Waveforms: rh+ vs Time')
plt.xlabel('Time (sec)')
plt.ylabel('rh+ (cm)')
plt.legend()
plt.grid()
plt.show()
plt.figure(figsize=(10, 6))
plt.plot(df1['t (sec)'], df1['rhx (cm)'], alpha=0.5, label='Simulation 1 (γ=3.0)')
plt.plot(df2['t (sec)'], df2['rhx (cm)'], alpha=0.5, label='Simulation 2 (γ=2.0)')
plt.plot(df3['t (sec)'], df3['rhx (cm)'], alpha=0.5, label='Simulation 3 (γ=5/3)')
plt.plot(df4['t (sec)'], df4['rhx (cm)'], alpha=0.5, label='Simulation 4 (γ=3.0)')
plt.plot(df5['t (sec)'], df5['rhx (cm)'], alpha=0.5, label='Simulation 5 (γ=5/3)')
plt.title('All Waveforms: rhx vs Time')
plt.xlabel('Time (sec)')
plt.ylabel('rhx (cm)')
plt.legend()
plt.grid()
plt.show()
#Lee W.H., 2000, Newtonian hydrodynamics of the coalescence of black holes with neutron stars -- III. Irrotational binaries with a stiff equation of state, Monthly Notices of the Royal Astronomical Society, Volume 318, Issue 2, Pages 606-617
#Lee W.H., 2001, Newtonian hydrodynamics of the coalescence of black holes with neutron stars -- IV. Irrotational binaries with a soft equation of state, Monthly Notices of the Royal Astronomical Society, Volume 328, Issue 2, Pages 583-600, https://doi.org/10.1046/j.1365-8711.2001.04898.x
#Lee W.H., Kluzniak W., 1999, Newtonian hydrodynamics of the coalescence of black holes with neutron stars -- I & II, Astrophysical Journal/Monthly Notices of the Royal Astronomical Society
#Gravitational Wave Polarization Context: https://thesis.library.caltech.edu/13851/8/Sudhi_thesis.pdf